# Generated by Django 2.2.26 on 2022-03-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libnav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='numCheckedOut',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkedOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_images/NONE.jpg', upload_to='profile_images'),
        ),
    ]
